// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVwAYLL7R_h_NsxLUrsqbBsP3WQ5Oi3g',
    appId: '1:312102492259:web:059b8a83001ad2e5188056',
    messagingSenderId: '312102492259',
    projectId: 'flutter-chat-app-c2ae3',
    authDomain: 'flutter-chat-app-c2ae3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c2ae3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0Bgs_SdnaC6-UUDfVkql-C3_5WpCS2A',
    appId: '1:312102492259:android:32c7d064aef71cfa188056',
    messagingSenderId: '312102492259',
    projectId: 'flutter-chat-app-c2ae3',
    storageBucket: 'flutter-chat-app-c2ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKatpIbknRlgoHRvPX4-CI5S6xe8R4c7E',
    appId: '1:312102492259:ios:b7fd4de09660589c188056',
    messagingSenderId: '312102492259',
    projectId: 'flutter-chat-app-c2ae3',
    storageBucket: 'flutter-chat-app-c2ae3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKatpIbknRlgoHRvPX4-CI5S6xe8R4c7E',
    appId: '1:312102492259:ios:3e2e63a6a4d83e8d188056',
    messagingSenderId: '312102492259',
    projectId: 'flutter-chat-app-c2ae3',
    storageBucket: 'flutter-chat-app-c2ae3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
